name: CI/CD for React App

on:
  push:
    branches:
      - '**'  # chạy cho mọi branch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      is_main: ${{ steps.check_branch.outputs.is_main }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.node_version }}

      - name: Check if branch is main
        id: check_branch
        run: |
          echo "Running on branch: ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build app
        run: npm run build

  deploy:
    needs: build
    if: needs.build.outputs.is_main == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Check dist folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "dist folder not found."
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload to S3
        run: aws s3 sync dist s3://funbug --delete


  test:
    needs: deploy
    if: needs.build.outputs.is_main == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
